### ISSUE TITLE
Consider adding hreflang to pages

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/hugo-module-tnd-seo#9]
We should review and come up with a specification for our multi-language sites for SEO

https://support.google.com/webmasters/answer/189077
https://yoast.com/hreflang-ultimate-guide/#hreflang-meant-for

e.g.
```
<link rel="alternate" href="http://example.com/" 
  hreflang="en" />
<link rel="alternate" href="http://example.com/en-gb/" 
  hreflang="en-gb" />
<link rel="alternate" href="http://example.com/en-au/" 
  hreflang="en-au" />
```
and
```
hreflang and rel=canonical

rel=”alternate” hreflang=”x”markup and rel=”canonical” can and should be used together. 
Every language should have a rel=”canonical” link pointing to itself. 
In the first example, this would look like this, assuming that we’re on the example.com homepage:

<link rel="canonical" href="http://example.com/">
<link rel="alternate" href="http://example.com/" 
  hreflang="en" />
<link rel="alternate" href="http://example.com/en-gb/" 
  hreflang="en-gb" />
<link rel="alternate" href="http://example.com/en-au/" 
  hreflang="en-au" />
```

**Comment by regisphilibert** [comment]
@budparr I transfered the issue to the new module.

**Comment by budparr** [comment]
@regisphilibert I've added some examples to the op. Basically the idea is if a page is translated we should also point to the page that it is translated from, with its language. Can you give me a sense of feasibility to implement soon?

**Comment by regisphilibert** [comment]
It's fairly trivial. I'm just curious about language code. We often use `en`, `fr` but the web is more used to `en-us`, `fr-fr`, `fr-ca` etc... 

This will not impact the work here, as we'll just use the `.languageCode` and trust Hugo's returned value.

I can take care of it now :)

**Comment by regisphilibert** [comment]
> Every language should have a rel=”canonical” link pointing to itself. 

@budparr that should already be the case. Did you find a case where this does not work? This is what we currenlty have: https://tnd-modules.netlify.app/modules/seo/

**Comment by budparr** [comment]
Nope. We're good on canonicals
